BUFFER_SIZE = 4096
FRAGMENT_SIZE = 1400
SENDING_WINDOW_SIZE = 80
CLIENT_SOCK_TIMEOUT = 0.70 # Can be set below RTT for the funny
CLIENT_SEG_TIMEOUT = 0.5
SERVER_SOCK_TIMEOUT = 0.60
OUTPUT_PATH = "./output/"

DEBUG = True